#default stuff if you don't provide anything
DEFAULT_TICKER = "AAPL"
DEFAULT_OPTION_TYPE = "call"
DEFAULT_STRIKE_PRICE = 150 
DEFAULT_START_DATE = "2023-01-01"
DEFAULT_END_DATE = "2024-01-01"
DEFAULT_RISK_FREE_RATE = 0.05 
DEFAULT_VOLATILITY = 0.25       
DEFAULT_TIME_TO_EXPIRY = 60/365
LOG_FILE = "options_backtest.log"
LOG_LEVEL = "INFO"